### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by nagababuthota984** [notashock/ToDo-Vanila#3]
give names to files and variables including CSS classes and ids **as meaningful as possible**. They should exactly represent what they are created for.

**Comment by nagababuthota984** [comment]
one such example is model.html. what does it represent is unclear.. come up with a name that describes what's that HTML page is for (should be concise, not too long)

**Comment by nagababuthota984** [comment]
one such example is model.html. what does it represent is unclear.. come up with a name that describes what's that HTML page is for (should be concise, not too long)

**Comment by notashock** [comment]
I've Done my best to give names to files and CSS classes and ids as well, if the issue didn't resolved. please let me know
